# Generated by Django 4.2.3 on 2023-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='file',
        ),
        migrations.AddField(
            model_name='event',
            name='is_vedio_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='vedio',
            field=models.FileField(blank=True, upload_to='event_image/video_link'),
        ),
    ]
