# Generated by Django 4.2.3 on 2023-07-29 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_remove_event_file_event_is_vedio_display_event_vedio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='is_vedio_display',
            new_name='is_video_display',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='vedio',
            new_name='video',
        ),
    ]
