# Generated by Django 4.2.3 on 2023-08-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_alumni_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='message',
            field=models.CharField(max_length=500),
        ),
    ]
