# Generated by Django 4.2.3 on 2023-09-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_gallery_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='photo',
            field=models.ImageField(blank=True, upload_to='Gallery'),
        ),
    ]
